#pragma once

CQSymbolMap g_ShaderSymbolMap = { {
	"HK_Scenery",
	"HK_Scenery_Skinned",
	"HK_Scenery_LOD",
	"HK_SceneryFarGround",
	"HK_Road",
	"HK_Terrain",
	"HK_Terrain_LOD",
	"HK_Vehicle",
	"HK_Vehicle_Glass",
	"HK_Vehicle_Decal",
	"HK_Vehicle_Wheel"
	"HK_Character",
	"HK_CharacterNIS",
	"HK_CharacterEye",
	"HK_Overlay",
	"HK_Foliage",
	"HK_CharacterHair",
	"Simple",
	"SimplePunch",
	"SimpleOpaque",
	"HK_Water",
	"Character",
	"ParticleBeam",
	"ParticleBeamSoftLit",
	"ParticleBeamSoftLitOcean",
	"ParticleLitShadow",
	"ParticlesoftLit",
	"ParticlesoftLitOcean",
	"ParticleSoft",
	"ParticleSoftUnalignedClipped",
	"ParticleUnalignedLit",
	"HK_Simple",
	"UberShader",
	"EmitDepth",
	"EmitDepth_Skinned",
	"HK_Highlight_SC",
	"HK_Highlight_SCSK",
}, true };